//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Mon Apr 21 2014 01:17:19
//
//      Input file      : 
//      Component name  : intadder_42_f300_uid15
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

module IntAdder_42_f300_uid15(clk, rst, X, Y, Cin, R);
   input         clk;
   input         rst;
   input [41:0]  X;
   input [41:0]  Y;
   input         Cin;
   output [41:0] R;
   /*
   always @(posedge clk)
      
         ;
   */
	assign R = X + Y + Cin;
   
endmodule
