//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Mon Apr 21 2014 01:17:53
//
//      Input file      : 
//      Component name  : intadder_27_f180_uid7
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

module IntAdder_27_f180_uid7(clk, rst, X, Y, Cin, R);
   input         clk;
   input         rst;
   input [26:0]  X;
   input [26:0]  Y;
   input         Cin;
   output [26:0] R;
   /*
   always @(posedge clk)
      
         ;
	*/
   assign R = X + Y + Cin;
   
endmodule
