//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Mon Apr 21 2014 01:17:19
//
//      Input file      : 
//      Component name  : intadder_33_f300_uid23
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

module IntAdder_33_f300_uid23(clk, rst, X, Y, Cin, R);
   input         clk;
   input         rst;
   input [32:0]  X;
   input [32:0]  Y;
   input         Cin;
   output [32:0] R;
   reg [32:0]    X_d1;
   reg [32:0]    Y_d1;
   reg           Cin_d1;
   
   always @(posedge clk)
      
      begin
         X_d1 <= X;
         Y_d1 <= Y;
         Cin_d1 <= Cin;
      end
   assign R = X_d1 + Y_d1 + Cin_d1;
   
endmodule
